### ISSUE TITLE
Selection of availability zones in failover ARM template

### ISSUE THREAD

**Issue by aitg-ap** [F5Networks/f5-azure-arm-templates-v2#21]
I have a customer looking to deploy an HA cluster across multiple availability zones such as member 1 in zone 3 and member 2 in zone 2.  The current failover arm template only supports a boolean logic value of true/false and if true is selected zone 1 is the only option.

Can this failover arm template be updated to support the deployment of the VMs across zones 1, 2 or 3?

**Comment by mikeshimkus** [comment]
Hi @aitg-ap, this can be accomplished now by editing the zone passed by the parent template here: https://github.com/F5Networks/f5-azure-arm-templates-v2/blob/9a977c99267a6daf874b4494b430a7c33878d78b/examples/failover/azuredeploy.json#L616

And here: https://github.com/F5Networks/f5-azure-arm-templates-v2/blob/9a977c99267a6daf874b4494b430a7c33878d78b/examples/failover/azuredeploy.json#L730

Since this is a change to the parent template, you wouldn't need to host customized templates anywhere; you can use the UI or Azure CLI (using the --template-file flag instead of --template-uri).

**Comment by aitg-ap** [comment]
Thanks.  In this template it seems like there is no definition of what subnet or vnet parameters should be used vs. the azuredeploy-existing-network.json template we currently using.  For the failover/azuredeploy.json template we want to use to select availability zones, where do we define these network parameters?  If it's auto populating, what values the template generating?

**Comment by mikeshimkus** [comment]
That's correct, when using the full stack template (azuredeploy.json) the vnet/subnet settings are defined as template variables here: https://github.com/F5Networks/f5-azure-arm-templates-v2/blob/9a977c99267a6daf874b4494b430a7c33878d78b/examples/failover/azuredeploy.json#L215

Which are passed to the network module to create the resources: https://github.com/F5Networks/f5-azure-arm-templates-v2/tree/main/examples/modules/network.

To change the network address of the vNet, you would update the vNetPrefix variable (and the template input params for IP addresses such as bigIpExternalSelfIp01).

**Comment by shyawnkarim** [comment]
Closing. Please open another issue if more assistance is needed.
